---
name: Build
on:
  push:
    branches:
      - develop
      - main
      - master

jobs:  
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set up Python 3.
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        if: steps.semantic.outputs.new-release-published == 'true'
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        if: steps.semantic.outputs.new-release-published == 'true'
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
